---
spring:
  datasource:
    url: jdbc:mysql://localhost/test?createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: false
    properties:
      generate-ddl: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format_sql: false


logging:
  level:
    root: INFO
    de.oglimmer: DEBUG
    org.hibernate.SQL: DEBUG
